### ISSUE TITLE
 Inquiry About ndata and Treefile Settings in MCMCTree

### ISSUE THREAD

**Issue by xueqinerer** [dosreislab/mcmctree#1]
I have a question regarding the settings for the ndata and treefile in the MCMCTree software. If I have 400 genes in my analysis, should I set ndata to 400? Additionally, does the treefile need to contain 400 separate trees, one for each gene alignment?

Thank you for your assistance.

**Comment by mariodosreis** [comment]
Hi @xueqinerer, for general use questions it is best to post this in the PAML's google group: https://groups.google.com/g/pamlsoftware. Parameter `ndata` controls the number of partitions in the program, this must match the number of partitions in the aligment file. Running 400 genes as separate partitions would be too computationally demanding. Please see examples in our papers in which genes are grouped into rate categories. We usually use `ndata = 4` or `ndata = 5` (4 or 5 partitions). Closing this, as this is not a software issue.

**Comment by xueqinerer** [comment]
thank you very much.

**Comment by xueqinerer** [comment]
Dear,

I'm applying to join the PAML's google group, waiting to be approved.I hope this email finds you well. I am currently working on divergence time estimation using both MCMCTree and TreePL, and I have encountered an issue where the divergence times estimated using the same calibration points differ by nearly 20 million years.

In particular, I would like to understand the factors that could influence the divergence time estimates obtained from MCMCTree. Since MCMCTree provides a time tree with confidence intervals, I am wondering which specific parameters in the mcmctree.ctl file could have the most significant impact on the final results.

Could you kindly provide some insight into which values in the mcmctree.ctl file I should pay special attention to, in order to better understand how they influence the divergence time estimation?

Any guidance you could offer would be greatly appreciated.Thank you very much.

Best regards







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dosreislab/mcmctree"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月12日(星期四) 晚上9:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dosreislab/mcmctree]  Inquiry About ndata and Treefile Settings in MCMCTree (Issue #1)





 
Hi @xueqinerer, for general use questions it is best to post this in the PAML's google group: https://groups.google.com/g/pamlsoftware. Parameter ndata controls the number of partitions in the program, this must match the number of partitions in the aligment file. Running 400 genes as separate partitions would be too computationally demanding. Please see examples in our papers in which genes are grouped into rate categories. We usually use ndata = 4 or ndata = 5 (4 or 5 partitions). Closing this, as this is not a software issue.

**Comment by mariodosreis** [comment]
Hi @xueqinerer, I wrote a blog post with common issues in mcmctree: https://dosreislab.github.io/2021/03/29/mcmctree-help.html. The number of issues that can affect a molecular clock analysis are simply too large to list here. You can try things like running the analysis with different rate priors (`rgene_gamma`), different prior for the diffusion parameters (`sigma2_gamma`), different ways to represent the fossils (i.e., `B` vs `L` calibrations), clock models (i.e., ILN vs GBM) and so on. You also need to read the many papers written on MCMCtree and learn them. 

Please do not use github issues for general use questions. This issue is closed. Further questions will be ignored and no replies to this thread will be provided.
